# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e324840d-3283-4884-8a79-f16f059c77ee";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cf6c45a6-e7fc-4d1f-bfeb-e3f9b451afcf";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DFAC-B1AD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f44e3bd3-7890-4e20-aa8f-0a1fdb2254be"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  fileSystems."/mnt/D" = {
    device = "UUID=1ff72dc8-8c84-4aef-aa33-398cae4cbe22";
    fsType = "ext4";
  };

  fileSystems."/mnt/R" = {
    device = "UUID=e1a23b15-c045-44b6-8d77-9109c64be2b4";
    fsType = "ext4";
  };

  fileSystems."/mnt/P" = {
    device = "UUID=a74eee73-1c55-4f5c-b456-f3c30a9fdca3";
    fsType = "btrfs";
  };

}
